// <copyright file="GPGSIds.cs" company="Google Inc.">
// Copyright (C) 2015 Google Inc. All Rights Reserved.
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//  http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//    limitations under the License.
// </copyright>

///
/// This file is automatically generated DO NOT EDIT!
///
/// These are the constants defined in the Play Games Console for Game Services
/// Resources.
///


public static class GPGSIds
{
        public const string achievement_major_convergence = "CgkIjP3qhoIaEAIQAw"; // <GPGSID>
        public const string achievement_crushing_victory = "CgkIjP3qhoIaEAIQAQ"; // <GPGSID>
        public const string achievement_arcane_harmony = "CgkIjP3qhoIaEAIQBA"; // <GPGSID>
        public const string achievement_arcane_cataclysm = "CgkIjP3qhoIaEAIQCA"; // <GPGSID>
        public const string achievement_critical_spell = "CgkIjP3qhoIaEAIQCQ"; // <GPGSID>
        public const string achievement_perfect_ritual = "CgkIjP3qhoIaEAIQBQ"; // <GPGSID>
        public const string achievement_first_ritual = "CgkIjP3qhoIaEAIQAA"; // <GPGSID>
        public const string achievement_ritual_master = "CgkIjP3qhoIaEAIQBg"; // <GPGSID>
        public const string achievement_unleashed_power = "CgkIjP3qhoIaEAIQBw"; // <GPGSID>
        public const string achievement_archmage = "CgkIjP3qhoIaEAIQAg"; // <GPGSID>

}

